trigger:
- master

pool:
  vmImage: 'ubuntu-latest'



steps:
- script: echo 'Go Build-WG'
  displayName: "GO Build"

- task: GoTool@0
  displayName: 'Use Go 1.10'

- task: Go@0
  displayName: 'go build'
  inputs:
    command: build
    arguments: '-o "$(System.TeamProject).exe"'
    workingDirectory: apis/trips



